In [2]:
import numpy as np

## create arrys using numpy
# create 1 1d array

arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)


[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [ ]:
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5) # 1 row 5 cols


array([[1, 2, 3, 4, 5]])

In [ ]:
#2d array
arr3=np.array([[1,2,3,4,5],[7,6,4,8,7]])
print(arr3)
print(arr3.shape)

[[1 2 3 4 5]
 [7 6 4 8 7]]
(2, 5)


In [ ]:
# arrange creates an array start from 0 to 10 with stepsize 2 and reshape creates 5 rows put elment there
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [ ]:
# creates arr with 5 rows and 2 cols with all values are 1
np.ones((5,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [17]:
# identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# atributes of numpy array
arr=np.array([[1,2,3],[4,5,6]])
print("array:",arr)
print("shape:",arr.shape)
print("number of dimensions",arr.ndim)
print("size(number of elements)",arr.size)
print("data type:",arr.dtype)
print("item size (in bytes):",arr.itemsize)


array: [[1 2 3]
 [4 5 6]]
shape: (2, 3)
number of dimensions 2
size(number of elements) 6
data type: int64
item size (in bytes): 8


In [ ]:
# Numpy vectorized operation
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

# element wise addition
print("addition",arr1+arr2)

# element wise subtraction
print("subtraction",arr1-arr2) # return type is array



addition [11 22 33 44 55]
subtraction [ -9 -18 -27 -36 -45]


In [22]:
#universal function
arr=np.array([2,3,4,5,6])
# square root
print(np.sqrt(arr))

#exponential
print(np.exp(arr))

#sine
print(np.sin(arr))

#natural log
print(np.log)

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
<ufunc 'log'>


In [25]:
# array slicing and indexing
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("array:\n",arr)

array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [26]:
arr[1:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [27]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [28]:
arr[0:2,2:]

array([[3, 4],
       [7, 8]])

In [29]:
arr[1:,1:3]

array([[ 6,  7],
       [10, 11]])

In [30]:
# modify array element
arr[0,0]=100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [31]:
arr[1:]=100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [ ]:
# statistical concept -- normalization
# to have a mean of 0 and standard deviation of 1
data=np.array([1,2,3,4,5])

#calculate mean and standard deviation
mean=np.mean(data)
std_dev=np.std(data)

# Normalize the data
normalized_data=(data - mean) / std_dev ## formula to normalize data
print("normalized data: ",normalized_data)

normalized data:  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [33]:
data = np.array([1, 2, 3, 4, 5, 16, 7, 8, 9, 10])

# Mean
mean = np.mean(data)
print("Mean:", mean)

# Median
median = np.median(data)
print("Median:", median)

# Standard deviation
std_dev = np.std(data)
print("Standard Deviation:", std_dev)

# Variance
variance = np.var(data)
print("Variance:", variance)



Mean: 6.5
Median: 6.0
Standard Deviation: 4.272001872658765
Variance: 18.25


In [34]:
## Logical operation
data=np.array([1,2,3,4,5,6,7,8,9,10])

data[(data>=5) & (data<=8)]

array([5, 6, 7, 8])